name: Verify Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Verify package.json
      run: |
        if [ -f "package.json" ]; then
          echo "✓ package.json exists"
          if jq empty package.json 2>/dev/null; then
            echo "✓ package.json is valid JSON"
          else
            echo "✗ package.json is not valid JSON"
            exit 1
          fi
        else
          echo "✗ package.json not found"
          exit 1
        fi
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install --legacy-peer-deps || (echo "Failed to install dependencies" && exit 1)
      
    - name: Generate Prisma Client
      run: npx prisma generate
      
    - name: Build
      run: npm run build
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
        BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
        UPLOADTHING_SECRET: ${{ secrets.UPLOADTHING_SECRET }}
        UPLOADTHING_APP_ID: ${{ secrets.UPLOADTHING_APP_ID }}
        NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
